- name: demo on loops
  hosts: local
  connection: local
  tasks: 
  - names: print names
    ansible.builtin.debug:
      msg: "Hello {{ item }}"
    loop:
    - Ramesh
    - Rajesh
    - Sri
    - Vysh
    