- name: demo on filters
  hosts: local
  connection: local
  vars: 
    topics: linux, shell, ansible, terraform
    tagmap:
      name: ansible
      project: roboshop
      component: catalogue 
    taglist: 
       [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
    ]

  tasks: 
  - name: greetings
    ansible.builtin.debug:
      msg: "Hi Sri, {{ GREETING | default('Good Morning') }}"

  - name: greetings
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"
  
  - name: map to list
    ansible.builtin.debug:
      msg: "{{ tagmap | dict2items }}"

  - name: list to map
    ansible.builtin.debug:
      msg: "{{ taglist | items2dict }}"