- name: read yaml file and convert to json
  hosts: local
  connection: local
  tasks: 
  - name: read students yaml file
    ansible.builtin.set_fact:       # setting a dynamic variable
      student_yaml: "{{ lookup('file', 'students.yaml') | from_yaml }}"
  
  
  - name: conert yaml to json
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_nice_json }}"